spring.application.name=database 
spring.datasource.url=jdbc:postgresql://localhost:5432/quickstart_db
spring.datasource.username=postgres
spring.datasource.password=001907


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always